export const pageContent = {
  about: {
    eyebrow: "About Udaan World School",
    title: "Shaping Bright Futures Everyday",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1800&auto=format&fit=crop",
    body: [
      "Udaan World School blends academic excellence, discipline, values and innovation to create confident future leaders.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      heroBadgeIcon: "CalendarDays",
      sections: [
        {
          id: "about-story",
          type: "split",
          title: "A Premium Learning Space For Modern Students",
          eyebrow: "Who We Are",
          body:
            "Our campus is designed to nurture curiosity, character, creativity and academic strength. We focus on complete child development with modern methods and strong moral values.\n\nWith dedicated teachers, smart learning systems and activity-rich programs, students receive the foundation needed for lifelong success.",
          mediaUrl:
            "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop",
          secondaryMediaUrl:
            "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=900&auto=format&fit=crop",
          ctaLabel: "Contact Us",
          ctaHref: "/contact-us",
          theme: "light",
        },
        {
          id: "about-values",
          type: "cards",
          title: "",
          body: "",
          theme: "dark",
          columns: 2,
          items: [
            {
              title: "Our Vision",
              text: "To become a center of excellence that empowers every learner to lead with knowledge, integrity and innovation.",
              icon: "Eye",
            },
            {
              title: "Our Mission",
              text: "To provide world-class education through values, discipline, creativity and student-centered learning.",
              icon: "Target",
            },
          ],
        },
        {
          id: "about-stats",
          type: "stats",
          theme: "soft",
          items: [
            { label: "Students", value: "2500+", icon: "Users" },
            { label: "Faculty", value: "120+", icon: "GraduationCap" },
            { label: "Results", value: "98%", icon: "Trophy" },
            { label: "Programs", value: "30+", icon: "BookOpen" },
          ],
        },
        {
          id: "about-cta",
          type: "cta",
          title: "Join Udaan World School",
          body: "Give your child a future-ready education in a caring and inspiring environment.",
          ctaLabel: "Apply For Admission",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  daySchool: {
    eyebrow: "Learning Model",
    title: "Day School",
    body: [
      "Our day school programme gives students a structured academic routine supported by activities, reading, sports, values, and regular parent communication.",
      "The aim is to make each school day productive, joyful, and purposeful.",
    ],
    highlights: ["Morning assembly", "Smart classroom approach", "Sports and activities", "Regular assessments"],
  },
  residential: {
    eyebrow: "Care",
    title: "Residential Facilities",
    body: [
      "This page is ready for hostel or day-boarding details when the school finalizes the content.",
      "For now, use it to show safety, meals, routines, wardens, medical support, and parent communication.",
    ],
    highlights: ["Safe environment", "Healthy food", "Mentor support", "Structured routine"],
  },
  knowledgePartners: {
    eyebrow: "Collaborations",
    title: "Knowledge Partners",
    body: [
      "Show your academic, skill-development, sports, technology, and enrichment partners here.",
      "This section can later be managed from the admin panel with partner logos and links.",
    ],
    highlights: ["Academic partners", "Skill partners", "Technology partners", "Sports mentors"],
  },
  founders: {
    eyebrow: "Founders Vision",
    title: "The Minds Behind\nUdaan World School",
    image:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1800&auto=format&fit=crop",
    body: [
      "A dream to build a school where students rise with confidence, values and world-class education.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "founder-message",
          type: "split",
          title: "Building Futures With Purpose",
          eyebrow: "Founder's Message",
          body:
            "Udaan World School was established with a vision to provide quality education that blends academics with strong character and practical life skills.\n\nWe believe every child carries unique potential. Our mission is to nurture that potential through guidance, innovation and a caring environment.\n\nOur commitment remains constant - to shape students who are knowledgeable, responsible and ready to lead.",
          mediaUrl:
            "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200&auto=format&fit=crop",
          secondaryMediaUrl:
            "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200&auto=format&fit=crop",
          signatureName: "Founder Name",
          signatureRole: "Founder, Udaan World School",
          quoteBadge: true,
          theme: "light",
        },
        {
          id: "founder-principles",
          type: "cards",
          title: "Principles We Stand For",
          body:
            "Our institution grows on values that guide every decision and every child's journey.",
          theme: "dark",
          columns: 3,
          align: "center",
          variant: "premium-centered",
          items: [
            {
              title: "Values First",
              text: "Education rooted in character, discipline and integrity.",
              icon: "HeartHandshake",
            },
            {
              title: "Excellence",
              text: "Commitment to high standards in academics and growth.",
              icon: "Trophy",
            },
            {
              title: "Innovation",
              text: "Modern learning methods for future-ready students.",
              icon: "Lightbulb",
            },
          ],
        },
        {
          id: "founder-cta",
          type: "cta",
          title: "Become Part Of Our Vision",
          body:
            "Join a school committed to excellence, values and future-ready education.",
          ctaLabel: "Apply Today",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  chairman: {
    eyebrow: "Director's Desk",
    title: "Message From The\nDirector",
    image:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1800&auto=format&fit=crop",
    body: [
      "Guiding the institution with vision, integrity and commitment to educational excellence.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "chairman-message",
          type: "split",
          title: "Education With Vision & Responsibility",
          eyebrow: "Director's Message",
          body:
            "At Udaan World School, we believe education is the foundation of a progressive society. Our aim is to create learners who are knowledgeable, compassionate and courageous.\n\nWe continuously invest in modern learning environments, experienced educators and holistic development programs so every child receives the best opportunities.\n\nI warmly invite families to become a part of this journey toward excellence and values.",
          mediaUrl:
            "https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=1200&auto=format&fit=crop",
          secondaryMediaUrl:
            "https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=1200&auto=format&fit=crop",
          signatureName: "Director Name",
          signatureRole: "Director, Udaan World School",
          quoteBadge: true,
          theme: "light",
        },
        {
          id: "chairman-focus",
          type: "cards",
          title: "Our Leadership Focus",
          body:
            "Core principles that shape our educational direction and long-term vision.",
          theme: "dark",
          columns: 3,
          align: "center",
          variant: "premium-centered",
          items: [
            {
              title: "Strong Values",
              text: "Education that builds ethics, respect and responsibility.",
              icon: "ShieldCheck",
            },
            {
              title: "High Standards",
              text: "A culture of excellence in academics and life skills.",
              icon: "Trophy",
            },
            {
              title: "Future Ready",
              text: "Innovation-driven learning for tomorrow's leaders.",
              icon: "Lightbulb",
            },
          ],
        },
        {
          id: "chairman-cta",
          type: "cta",
          title: "Join Our Educational Journey",
          body:
            "Build your child's future in an institution driven by leadership and excellence.",
          ctaLabel: "Apply Now",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  principal: {
    eyebrow: "Principal's Desk",
    title: "A Message From The\nPrincipal",
    image:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1800&auto=format&fit=crop",
    body: [
      "Nurturing students with discipline, care and a deep commitment to meaningful learning.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "principal-message",
          type: "split",
          title: "Learning With Discipline And Care",
          eyebrow: "Principal's Message",
          body:
            "A school becomes meaningful when students feel safe, challenged, supported, and inspired every day.\n\nOur academic team works to create a balanced environment of study, sports, values, and creativity.\n\nWe remain committed to helping every child grow into a thoughtful, confident and capable learner.",
          mediaUrl:
            "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200&auto=format&fit=crop",
          secondaryMediaUrl:
            "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200&auto=format&fit=crop",
          signatureName: "Principal Name",
          signatureRole: "Principal, Udaan World School",
          quoteBadge: true,
          theme: "light",
        },
        {
          id: "principal-focus",
          type: "cards",
          title: "Our Academic Focus",
          body:
            "The principles that guide teaching, mentoring and student development every day.",
          theme: "dark",
          columns: 3,
          align: "center",
          variant: "premium-centered",
          items: [
            {
              title: "Student Care",
              text: "A safe, supportive and encouraging environment for every learner.",
              icon: "ShieldCheck",
            },
            {
              title: "Academic Focus",
              text: "Strong fundamentals, discipline and clarity in learning.",
              icon: "Trophy",
            },
            {
              title: "Holistic Growth",
              text: "Balanced development through values, creativity and leadership.",
              icon: "Lightbulb",
            },
          ],
        },
        {
          id: "principal-cta",
          type: "cta",
          title: "Begin Your Child's Learning Journey",
          body:
            "Join a school that values care, discipline and future-ready education.",
          ctaLabel: "Apply Now",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  seniorLeaderTeam: {
    eyebrow: "Leadership Team",
    title: "Meet Our Senior\nLeadership Team",
    image:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1800&auto=format&fit=crop",
    body: [
      "Dedicated educators and visionary leaders guiding Udaan World School toward excellence.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "leader-team-grid",
          type: "cards",
          title: "Inspiring Leaders",
          body:
            "A passionate leadership group focused on quality education and student development.",
          theme: "light",
          columns: 4,
          align: "center",
          variant: "leaders-grid",
          items: [
            {
              title: "Dr. A. Sharma",
              subtitle: "Chairman",
              image:
                "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=900&auto=format&fit=crop",
            },
            {
              title: "Mrs. R. Verma",
              subtitle: "Principal",
              image:
                "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=900&auto=format&fit=crop",
            },
            {
              title: "Mr. S. Kapoor",
              subtitle: "Vice Principal",
              image:
                "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=900&auto=format&fit=crop",
            },
            {
              title: "Ms. P. Singh",
              subtitle: "Academic Head",
              image:
                "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=900&auto=format&fit=crop",
            },
          ],
        },
        {
          id: "leader-team-values",
          type: "cards",
          title: "",
          body: "",
          theme: "dark",
          columns: 3,
          align: "center",
          variant: "premium-centered",
          items: [
            {
              title: "Experienced Leadership",
              text: "A team committed to progress, discipline and student success.",
              icon: "Users",
            },
            {
              title: "Quality Standards",
              text: "Maintaining excellence in teaching, systems and outcomes.",
              icon: "Award",
            },
            {
              title: "Student First Approach",
              text: "Every decision is made for learner growth and wellbeing.",
              icon: "GraduationCap",
            },
          ],
        },
        {
          id: "leader-team-cta",
          type: "cta",
          title: "Learn With Trusted Leaders",
          body:
            "Join a school led by experienced educators committed to your child's future.",
          ctaLabel: "Apply Today",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  mandatoryDisclosure: {
    eyebrow: "Compliance",
    title: "Mandatory Public Disclosure",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Official school records, certificates, fee structure, admission process and public information.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "disclosure-general",
          type: "infoPanel",
          title: "General Information",
          label: "A : GENERAL INFORMATION",
          image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { icon: "School", text: "Udaan World School" },
            { icon: "MapPin", text: "Tewari's Richolla Farm, Baheri, Bareilly, Uttar Pradesh - 243201" },
            { icon: "Phone", text: "+91 8650105946, +91 7351171361" },
            { icon: "Mail", text: "udaanworldschool@gmail.com" },
          ],
          extraLines: [
            "Principal: Mr. Balwant Singh",
            "Director: Mrs. Naina Tewari",
          ],
        },
        {
          id: "disclosure-documents",
          type: "documentsTable",
          title: "Documents",
          label: "B : DOCUMENTS AND INFORMATION",
          items: [
            { name: "Recognition Certificate", fileUrl: "#" },
            { name: "NOC Certificate", fileUrl: "#" },
            { name: "Building Safety Certificate", fileUrl: "#" },
            { name: "Fire Safety Certificate", fileUrl: "#" },
            { name: "Water & Sanitation Certificate", fileUrl: "#" },
            { name: "Trust Registration Certificate", fileUrl: "#" },
            { name: "Affiliation Documents", fileUrl: "#" },
            { name: "Staff Details", fileUrl: "#" },
            { name: "Academic Calendar", fileUrl: "#" },
            { name: "Transfer Certificate Format", fileUrl: "#" },
          ],
        },
        {
          id: "disclosure-fees",
          type: "simpleTable",
          title: "Fee Structure",
          label: "C : FEE STRUCTURE",
          headers: ["Class / Charges", "Amount"],
          items: [
            { label: "Form Fees", value: "₹600" },
            { label: "Admission Fee", value: "₹5000" },
            { label: "Annual Charges", value: "₹2600" },
            { label: "Exam Fee", value: "₹2000" },
            { label: "Nursery", value: "₹1300" },
            { label: "LKG", value: "₹1400" },
            { label: "UKG", value: "₹1450" },
            { label: "Class I", value: "₹1550" },
            { label: "Class II", value: "₹1650" },
            { label: "Class III", value: "₹1700" },
            { label: "Class IV", value: "₹1750" },
            { label: "Class V", value: "₹1850" },
            { label: "Class VI", value: "₹1900" },
            { label: "Class VII", value: "₹1980" },
            { label: "Class VIII", value: "₹2030" },
            { label: "Class IX", value: "₹2500" },
            { label: "Class X", value: "₹2500" },
            { label: "XI Commerce", value: "₹3100" },
            { label: "XI Science", value: "₹3300" },
            { label: "XII Commerce", value: "₹3500" },
            { label: "XII Science", value: "₹3700" },
          ],
        },
        {
          id: "disclosure-process",
          type: "textList",
          title: "Admission Process",
          label: "D : ADMISSION PROCESS",
          items: [
            { text: "1. Enquiry & Registration" },
            { text: "2. Application Form Submission" },
            { text: "3. Interaction / Assessment" },
            { text: "4. Confirmation of Admission" },
            { text: "5. Document Verification" },
          ],
        },
        {
          id: "disclosure-age",
          type: "textList",
          title: "Age Criteria",
          label: "E : AGE CRITERIA",
          items: [
            { text: "Nursery - 3+ Years" },
            { text: "LKG - 4+ Years" },
            { text: "UKG - 5+ Years" },
            { text: "Admission is granted according to class eligibility." },
          ],
        },
      ],
    },
  },
  events: {
    eyebrow: "School Activities",
    title: "Events & Celebrations",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Memorable moments, competitions, festivals and celebrations that build confidence, creativity and lifelong memories.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "event-highlights",
          type: "eventHighlights",
          title: "Upcoming Highlights",
          body:
            "Exciting school events designed to inspire, engage and celebrate every student.",
        },
        {
          id: "event-calendar",
          type: "cards",
          title: "Annual Calendar",
          body: "",
          theme: "dark",
          columns: 2,
          align: "left",
          variant: "calendar-grid",
          items: [
            { subtitle: "April", title: "New Session Begins" },
            { subtitle: "August", title: "Independence Day Celebration" },
            { subtitle: "October", title: "Science Exhibition" },
            { subtitle: "December", title: "Winter Carnival" },
            { subtitle: "January", title: "Sports Meet" },
            { subtitle: "March", title: "Annual Day & Farewell" },
          ],
        },
        {
          id: "event-gallery",
          type: "eventGallery",
          title: "Event Gallery",
          body: "A glimpse of celebrations and achievements.",
        },
        {
          id: "events-cta",
          type: "cta",
          title: "Join Our Next Event",
          body:
            "Become part of a vibrant school community full of learning and celebration.",
          ctaLabel: "Contact School",
          ctaHref: "/contact-us",
        },
      ],
    },
  },
  admissionProcedure: {
    eyebrow: "Admissions",
    title: "Admission Procedure",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "A smooth and transparent admission process designed for parents and students.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "admission-steps",
          type: "cards",
          title: "Simple 4 Step Process",
          body: "",
          theme: "light",
          columns: 2,
          align: "left",
          variant: "process-grid",
          items: [
            {
              title: "Enquiry & Registration",
              text: "Visit the campus or submit an online enquiry form to begin the admission process.",
              icon: "FileText",
            },
            {
              title: "Form Submission",
              text: "Fill out the admission form and submit required student documents.",
              icon: "UserCheck",
            },
            {
              title: "Interaction / Assessment",
              text: "Student interaction or basic academic assessment (if applicable).",
              icon: "BadgeCheck",
            },
            {
              title: "Fee Submission",
              text: "Complete admission by depositing applicable fees after confirmation.",
              icon: "CreditCard",
            },
          ],
        },
        {
          id: "admission-documents",
          type: "textList",
          title: "Required Documents",
          body: "",
          theme: "dark",
          variant: "checklist-split",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Birth Certificate" },
            { text: "Aadhar Card Copy" },
            { text: "Previous School Report Card" },
            { text: "Transfer Certificate (if applicable)" },
            { text: "Passport Size Photographs" },
            { text: "Parent ID Proof" },
          ],
        },
        {
          id: "admission-age",
          type: "cards",
          title: "Age Criteria",
          body: "",
          theme: "light",
          columns: 3,
          align: "left",
          variant: "age-grid",
          items: [
            { title: "Nursery", subtitle: "3+ Years" },
            { title: "LKG", subtitle: "4+ Years" },
            { title: "UKG", subtitle: "5+ Years" },
          ],
        },
        {
          id: "admission-cta",
          type: "cta",
          title: "Start Admission Today",
          body: "Limited seats available. Secure your child’s bright future now.",
          ctaLabel: "Apply Now",
          ctaHref: "/contact",
        },
      ],
    },
  },
  academics: {
    eyebrow: "Academics",
    title: "Curriculum",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "A balanced curriculum that blends academics, creativity, discipline and future skills.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "curriculum-vision",
          type: "textList",
          title: "Learning Beyond Books",
          body: "Our curriculum focuses on concept clarity, communication, confidence, discipline and problem solving from early years to senior grades.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Academic Vision",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "NCERT / Board aligned syllabus" },
            { text: "Concept based teaching" },
            { text: "Regular tests & assessments" },
            { text: "Activity based learning" },
            { text: "Smart classroom integration" },
            { text: "Personal attention to students" },
          ],
        },
        {
          id: "academic-stages",
          type: "cards",
          title: "Academic Stages",
          body: "",
          theme: "dark",
          columns: 2,
          align: "left",
          variant: "default",
          items: [
            {
              title: "Pre Primary",
              subtitle: "Nursery • LKG • UKG",
              text: "Play-based learning focused on language, numbers, creativity and confidence.",
            },
            {
              title: "Primary Wing",
              subtitle: "Class I - V",
              text: "Strong fundamentals in English, Maths, EVS, Computer and co-curricular growth.",
            },
            {
              title: "Middle Wing",
              subtitle: "Class VI - VIII",
              text: "Concept clarity, practical learning, discipline and analytical thinking.",
            },
            {
              title: "Senior Wing",
              subtitle: "Class IX - XII",
              text: "Board preparation, career focus, advanced academics and leadership skills.",
            },
          ],
        },
        {
          id: "core-subjects",
          type: "cards",
          title: "Core Subjects",
          body: "",
          theme: "light",
          columns: 3,
          align: "center",
          variant: "subject-grid",
          items: [
            { title: "English" },
            { title: "Hindi" },
            { title: "Mathematics" },
            { title: "Science" },
            { title: "Social Science" },
            { title: "Computer Science" },
            { title: "General Knowledge" },
            { title: "Art & Craft" },
            { title: "Physical Education" },
          ],
        },
        {
          id: "curriculum-skills",
          type: "cards",
          title: "",
          body: "",
          theme: "light",
          columns: 4,
          align: "left",
          variant: "icon-title-grid",
          items: [
            { title: "Critical Thinking", icon: "Brain" },
            { title: "Digital Learning", icon: "MonitorSmartphone" },
            { title: "Creative Skills", icon: "PenTool" },
            { title: "Team Building", icon: "Users" },
          ],
        },
      ],
    },
  },
  results: {
    eyebrow: "Academics",
    title: "Academic Results",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Celebrating academic excellence, student success and consistent outstanding performance.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "results-metrics",
          type: "cards",
          title: "",
          body: "",
          theme: "light",
          columns: 4,
          align: "center",
          variant: "metric-stats",
          items: [
            { title: "98%", subtitle: "Board Result" },
            { title: "92%", subtitle: "First Division" },
            { title: "97.8%", subtitle: "Top Score" },
            { title: "40+", subtitle: "University Selections" },
          ],
        },
        {
          id: "star-performers",
          type: "cards",
          title: "Star Performers",
          body: "Proud achievers of Udaan World School.",
          theme: "dark",
          columns: 3,
          align: "center",
          variant: "topper-grid",
          items: [
            {
              title: "Aarav Sharma",
              subtitle: "Class X",
              text: "97.8%",
              image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
              icon: "Topper",
            },
            {
              title: "Ananya Singh",
              subtitle: "Class XII Science",
              text: "96.4%",
              image: "/director.jpg",
              icon: "Topper",
            },
            {
              title: "Rohan Verma",
              subtitle: "Class XII Commerce",
              text: "95.9%",
              image: "/principal.jpg",
              icon: "Topper",
            },
          ],
        },
        {
          id: "results-growth",
          type: "simpleTable",
          title: "Yearly Growth",
          body: "Our consistent performance reflects strong teaching systems, student dedication and focused academic mentoring.",
          label: "",
          headers: ["Year", "Result"],
          variant: "growth-split",
          sideTitle: "Excellence Continues",
          sideBody: "We prepare students for boards, competitive exams and future careers with confidence.",
          sideIcon: "TrendingUp",
          items: [
            { label: "2026", value: "98% Overall Result" },
            { label: "2025", value: "96% Overall Result" },
            { label: "2024", value: "95% Overall Result" },
            { label: "2023", value: "94% Overall Result" },
          ],
        },
        {
          id: "results-cta",
          type: "cta",
          title: "Be Our Next Topper",
          body: "Join a school where performance meets purpose.",
          ctaLabel: "Apply Now",
          ctaHref: "/admissions/enquiry",
          variant: "dark-icon",
          icon: "GraduationCap",
        },
      ],
    },
  },
  academicFacilities: {
    eyebrow: "Facilities",
    title: "Academic Facilities",
    body: [
      "Show classrooms, labs, library, reading areas, activity rooms, and learning resources here.",
      "This page follows the same Udaan theme and can be expanded with real campus photos.",
    ],
    highlights: ["Classrooms", "Library", "Labs", "Activity rooms"],
  },
  smartClasses: {
    eyebrow: "Academics",
    title: "Smart Classes",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Digital classrooms designed to make learning interactive, effective and exciting.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "smart-vision",
          type: "textList",
          title: "Technology Meets Teaching",
          body: "Our smart classrooms transform traditional lectures into visual, engaging and concept-based experiences that students enjoy.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Modern Education",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Improves concentration" },
            { text: "Makes concepts easier" },
            { text: "Encourages participation" },
            { text: "Modern learning environment" },
            { text: "Faster understanding" },
            { text: "Future-ready students" },
          ],
        },
        {
          id: "smart-features",
          type: "cards",
          title: "Smart Learning Features",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            {
              title: "Interactive Boards",
              text: "Modern digital boards for visual and engaging lessons.",
              icon: "MonitorSmartphone",
            },
            {
              title: "Audio Visual Learning",
              text: "Videos, animations and simulations for better understanding.",
              icon: "CirclePlay",
            },
            {
              title: "Connected Classrooms",
              text: "Technology-enabled learning environment for every student.",
              icon: "Wifi",
            },
            {
              title: "Better Retention",
              text: "Students understand faster through visual teaching methods.",
              icon: "Brain",
            },
          ],
        },
        {
          id: "smart-future",
          type: "split",
          title: "Future Ready Students",
          body: "We prepare students to confidently use technology, think critically and adapt to modern academic environments.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Explore Academics",
          ctaHref: "/academics",
          sideTitle: "Digital Edge",
          sideBody: "Better visuals, stronger memory, higher engagement and improved outcomes.",
          sideIcon: "Laptop",
        },
      ],
    },
  },
  labs: {
    eyebrow: "Academics",
    title: "Laboratories",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Advanced labs that transform theory into practical knowledge and real skills.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "labs-vision",
          type: "textList",
          title: "Learn By Doing",
          body: "Our laboratories help students understand concepts deeply through observation, experimentation and exploration.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Practical Learning",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Practical concept understanding" },
            { text: "Scientific thinking development" },
            { text: "Technology exposure" },
            { text: "Confidence through experiments" },
            { text: "Skill based learning" },
            { text: "Future career readiness" },
          ],
        },
        {
          id: "lab-facilities",
          type: "cards",
          title: "Our Lab Facilities",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            {
              title: "Science Lab",
              text: "Hands-on experiments for Physics, Chemistry and Biology learning.",
              icon: "FlaskConical",
            },
            {
              title: "Computer Lab",
              text: "Modern systems for coding, typing, digital skills and research.",
              icon: "MonitorSmartphone",
            },
            {
              title: "Biology Lab",
              text: "Microscope studies, models and practical observation learning.",
              icon: "Microscope",
            },
            {
              title: "Innovation Zone",
              text: "Creative projects, robotics basics and problem-solving activities.",
              icon: "Cpu",
            },
          ],
        },
        {
          id: "labs-future",
          type: "split",
          title: "Explore & Discover",
          body: "Students build curiosity, logic and confidence while performing supervised practical activities.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Explore Academics",
          ctaHref: "/academics",
          sideTitle: "Innovation Starts Here",
          sideBody: "Practical education helps students remember, apply and grow beyond textbooks.",
          sideIcon: "Beaker",
        },
      ],
    },
  },
  coCurricular: {
    eyebrow: "Facilities",
    title: "Co-curricular Facilities",
    body: [
      "Co-curricular learning builds confidence, teamwork, creativity, and communication.",
      "Use this page for art, music, dance, debates, clubs, competitions, and personality development.",
    ],
    highlights: ["Art", "Music", "Clubs", "Competitions"],
  },
  scholarships: {
    eyebrow: "Admissions",
    title: "Scholarships",
    body: [
      "Use this page to explain scholarship rules, eligibility, merit criteria, and financial assistance.",
      "The content can be made editable in the admin panel.",
    ],
    highlights: ["Merit support", "Need-based support", "Eligibility", "Application process"],
  },
  sportsFacilities: {
    eyebrow: "Facilities",
    title: "Sports Facilities",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Building champions through sportsmanship, fitness, teamwork and discipline.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "sports-vision",
          type: "textList",
          title: "Play, Perform & Progress",
          body: "Our sports programs encourage physical fitness, confidence and a winning mindset. Students enjoy guided training and regular competitions.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Active Campus",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Cricket" },
            { text: "Football" },
            { text: "Basketball" },
            { text: "Badminton" },
            { text: "Volleyball" },
            { text: "Athletics" },
            { text: "Yoga" },
            { text: "Indoor Games" },
          ],
        },
        {
          id: "sports-values",
          type: "cards",
          title: "Why Sports Matter",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            {
              title: "Fitness",
              text: "Regular sports improve stamina, strength and health.",
              icon: "Dumbbell",
            },
            {
              title: "Leadership",
              text: "Team games develop responsibility and confidence.",
              icon: "Trophy",
            },
            {
              title: "Discipline",
              text: "Sports teach consistency, patience and focus.",
              icon: "Medal",
            },
            {
              title: "Teamwork",
              text: "Students learn cooperation and communication.",
              icon: "Users",
            },
          ],
        },
        {
          id: "sports-cta",
          type: "cta",
          title: "Train Like A Champion",
          body: "Encourage your child to stay active, healthy and confident through sports.",
          ctaLabel: "Apply Now",
          ctaHref: "/admission-enquiry",
          variant: "light-icon",
          icon: "Goal",
        },
      ],
    },
  },
  library: {
    eyebrow: "Facilities",
    title: "Library",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "A calm and inspiring reading space that builds imagination, focus and lifelong learning habits.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "library-vision",
          type: "textList",
          title: "A Space To Read & Reflect",
          body: "Our library encourages students to explore books, ideas and knowledge beyond the classroom.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Reading Culture",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Wide range of books" },
            { text: "Quiet reading environment" },
            { text: "Reference resources" },
            { text: "Reading habit development" },
            { text: "Student research support" },
            { text: "Language enrichment" },
          ],
        },
        {
          id: "library-features",
          type: "cards",
          title: "Library Highlights",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            { title: "Reading Zone", text: "A peaceful space where students can enjoy focused reading time.", icon: "BookOpen" },
            { title: "Reference Section", text: "Access to subject-based books, encyclopedias and learning material.", icon: "GraduationCap" },
            { title: "Student Access", text: "Age-appropriate collections that support curiosity and independent discovery.", icon: "Users" },
            { title: "Knowledge Growth", text: "A strong reading environment that improves language and confidence.", icon: "Sparkles" },
          ],
        },
        {
          id: "library-future",
          type: "split",
          title: "Readers Become Leaders",
          body: "A strong library culture helps children think deeply, express clearly and grow into informed learners.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Explore Academics",
          ctaHref: "/academics",
          sideTitle: "Learning Never Stops",
          sideBody: "Books open minds, strengthen imagination and support excellence in every subject.",
          sideIcon: "BookOpen",
        },
      ],
    },
  },
  transport: {
    eyebrow: "Facilities",
    title: "Transport",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Safe, reliable and student-friendly transport support for a smooth school journey every day.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "transport-vision",
          type: "textList",
          title: "Safe & Reliable Travel",
          body: "Our transport system is planned to help students commute comfortably with care, punctuality and supervision.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Daily Commute",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Well-planned routes" },
            { text: "Student safety focus" },
            { text: "Punctual pick-up and drop" },
            { text: "Responsible staff support" },
            { text: "Comfortable travel" },
            { text: "Parent peace of mind" },
          ],
        },
        {
          id: "transport-features",
          type: "cards",
          title: "Transport Features",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            { title: "School Buses", text: "Reliable bus service supporting students across nearby routes.", icon: "BusFront" },
            { title: "Safety Measures", text: "Supervised travel with systems that prioritize student wellbeing.", icon: "ShieldCheck" },
            { title: "Route Coverage", text: "Transport planning designed for convenience and accessibility.", icon: "MapPin" },
            { title: "Timely Movement", text: "Consistent schedules that support attendance and routine.", icon: "Clock3" },
          ],
        },
        {
          id: "transport-future",
          type: "split",
          title: "Travel With Confidence",
          body: "A dependable school transport system helps students arrive ready to learn and parents stay reassured.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Contact School",
          ctaHref: "/contact-us",
          sideTitle: "Safety On Every Route",
          sideBody: "Comfort, punctuality and care are built into every school journey.",
          sideIcon: "BusFront",
        },
      ],
    },
  },
  hostel: {
    eyebrow: "Facilities",
    title: "Hostel",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "A safe and caring residential environment that supports routine, discipline and student wellbeing.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "hostel-vision",
          type: "textList",
          title: "A Home Away From Home",
          body: "Our hostel environment is built to give students comfort, supervision and a healthy daily routine.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Residential Care",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Safe accommodation" },
            { text: "Structured daily routine" },
            { text: "Student supervision" },
            { text: "Study support" },
            { text: "Healthy living environment" },
            { text: "Personal growth and discipline" },
          ],
        },
        {
          id: "hostel-features",
          type: "cards",
          title: "Hostel Features",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            { title: "Safety First", text: "A secure environment where student wellbeing remains the top priority.", icon: "ShieldCheck" },
            { title: "Comfortable Stay", text: "A disciplined hostel setup that supports comfort and routine.", icon: "BedDouble" },
            { title: "Community Living", text: "Students learn sharing, teamwork and healthy social behavior.", icon: "Users" },
            { title: "Balanced Growth", text: "Study, care and values come together in a supportive environment.", icon: "HeartHandshake" },
          ],
        },
        {
          id: "hostel-future",
          type: "split",
          title: "Growing With Independence",
          body: "The hostel experience helps students develop responsibility, confidence and healthy habits for life.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Contact School",
          ctaHref: "/contact-us",
          sideTitle: "Safe Stay, Strong Values",
          sideBody: "A residential setting that supports both academic focus and personal development.",
          sideIcon: "BedDouble",
        },
      ],
    },
  },
  cafeteria: {
    eyebrow: "Facilities",
    title: "Cafeteria",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Nutritious meals and a clean dining environment that support student energy, focus and wellbeing.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "cafeteria-vision",
          type: "textList",
          title: "Healthy Meals Everyday",
          body: "Our cafeteria promotes hygiene, balanced nutrition and a student-friendly food environment.",
          theme: "light",
          variant: "checklist-split-light",
          eyebrow: "Healthy Dining",
          mediaUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
          items: [
            { text: "Clean dining space" },
            { text: "Balanced meals" },
            { text: "Student-friendly menu" },
            { text: "Hygiene focused service" },
            { text: "Nutritious food choices" },
            { text: "Energy for active learning" },
          ],
        },
        {
          id: "cafeteria-features",
          type: "cards",
          title: "Cafeteria Features",
          body: "",
          theme: "dark",
          columns: 4,
          align: "left",
          variant: "default",
          items: [
            { title: "Healthy Meals", text: "Food choices planned to support energy and student wellbeing.", icon: "UtensilsCrossed" },
            { title: "Hygiene Standards", text: "A clean and carefully managed dining setup for students.", icon: "ShieldCheck" },
            { title: "Student Comfort", text: "A welcoming cafeteria environment where students can eat and relax.", icon: "HeartHandshake" },
            { title: "Better Daily Routine", text: "Nutritious food supports focus, participation and healthy habits.", icon: "Sparkles" },
          ],
        },
        {
          id: "cafeteria-future",
          type: "split",
          title: "Fuel For Learning",
          body: "Healthy food habits help students stay active, focused and ready to make the most of every school day.",
          theme: "light",
          variant: "panel-split",
          ctaLabel: "Contact School",
          ctaHref: "/contact-us",
          sideTitle: "Nutrition Matters",
          sideBody: "A good meal supports concentration, health and positive daily performance.",
          sideIcon: "UtensilsCrossed",
        },
      ],
    },
  },
  photoGallery: {
    eyebrow: "Gallery Showcase",
    title: "Photo Gallery",
    body: "A curated glimpse into campus life, celebrations, student achievements and everyday moments at Udaan World School.",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    meta: {
      heroVariant: "full",
      heroBadgeIcon: "Sparkles",
      sections: [
        {
          id: "photo-gallery-grid",
          type: "managedGallery",
          title: "Photo Gallery",
          body: "School memories, classroom life and activity highlights managed from the admin gallery section.",
          source: "photos",
          mediaKind: "image",
          limit: 12,
        },
        {
          id: "photo-gallery-cta",
          type: "cta",
          title: "See School Life Up Close",
          body: "Visit the campus and experience the energy, creativity and discipline that shape every student journey.",
          variant: "light-icon",
          icon: "Sparkles",
          ctaLabel: "Book Campus Visit",
          ctaHref: "/contact-us",
        },
      ],
    },
  },
  videoGallery: {
    eyebrow: "Visual Stories",
    title: "Video Gallery",
    body: "Campus walkthroughs, event recordings, student performances and special school moments, all organised from the backend gallery manager.",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    meta: {
      heroVariant: "full",
      heroBadgeIcon: "CirclePlay",
      sections: [
        {
          id: "video-gallery-grid",
          type: "managedGallery",
          title: "Video Gallery",
          body: "Watch school stories, classroom experiences and event highlights through editable video showcases.",
          source: "videos",
          mediaKind: "video",
          limit: 9,
        },
        {
          id: "video-gallery-cta",
          type: "cta",
          title: "Explore Udaan In Motion",
          body: "Every video captures the confidence, creativity and discipline that define our campus life.",
          variant: "dark-icon",
          icon: "CirclePlay",
          ctaLabel: "Admission Enquiry",
          ctaHref: "/admission-enquiry",
        },
      ],
    },
  },
  eventsGallery: {
    eyebrow: "Celebrations",
    title: "Events Gallery",
    body: "A dedicated visual collection of annual functions, sports days, cultural celebrations and memorable school events.",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    meta: {
      heroVariant: "full",
      heroBadgeIcon: "CalendarDays",
      sections: [
        {
          id: "events-gallery-grid",
          type: "managedGallery",
          title: "Events Gallery",
          body: "Festival moments, stage performances and celebration highlights managed from the admin gallery backend.",
          source: "events",
          mediaKind: "image",
          limit: 12,
        },
        {
          id: "events-gallery-cta",
          type: "cta",
          title: "Be Part Of The Next Celebration",
          body: "Join a school community full of energy, participation and unforgettable student moments.",
          variant: "light-icon",
          icon: "CalendarDays",
          ctaLabel: "Explore Events",
          ctaHref: "/events",
        },
      ],
    },
  },
  careers: {
    eyebrow: "Careers",
    title: "Join Udaan World School",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1400&auto=format&fit=crop",
    body: [
      "Grow your teaching journey in a school that values discipline, creativity, student success and supportive leadership.",
      "Explore active openings below and apply directly with your resume from the careers page.",
    ],
    highlights: ["Teaching roles", "Resume upload", "Admin review", "Live job openings"],
  },
  blogs: {
    eyebrow: "Blogs",
    title: "School News And Learning Stories",
    body: [
      "Publish news, articles, achievements, event updates, parenting notes, and learning resources here.",
      "In the admin panel, blogs will be created, edited, and published dynamically.",
    ],
    highlights: ["News", "Articles", "Achievements", "Resources"],
  },
  terms: {
    eyebrow: "Policy",
    title: "Terms Of Services",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=1800&auto=format&fit=crop",
    body: [
      "These terms describe how visitors, parents, students and applicants may use the Udaan World School website and public school information.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "terms-overview",
          type: "split",
          eyebrow: "Website Use",
          title: "Clear Rules For Using School Information",
          body: "This website is provided for school communication, admissions guidance, academic updates, galleries, careers and official public information.\n\nVisitors may browse, read, enquire and download public files made available by the school. Misuse of forms, misleading submissions, scraping, impersonation and unauthorized copying of protected material are not allowed.",
          mediaUrl: "https://images.unsplash.com/photo-1453945619913-79ec89a82c51?q=80&w=1200&auto=format&fit=crop",
          theme: "light",
        },
        {
          id: "terms-principles",
          type: "cards",
          title: "Important Terms",
          body: "A quick view of the most important responsibilities and disclaimers.",
          theme: "dark",
          columns: 2,
          items: [
            {
              title: "Information Accuracy",
              text: "The school tries to keep content current, but schedules, fees, openings and notices may change when management updates them.",
              icon: "BadgeCheck",
            },
            {
              title: "Admissions & Enquiries",
              text: "Submitting an enquiry or application does not guarantee admission, selection, employment or immediate response.",
              icon: "FileText",
            },
            {
              title: "Media & Content",
              text: "Images, videos, branding and written content published by the school should not be reused commercially without permission.",
              icon: "Camera",
            },
            {
              title: "Responsible Use",
              text: "Users must not upload harmful files, fake details, abusive messages or content that disrupts school operations.",
              icon: "ShieldCheck",
            },
          ],
        },
        {
          id: "terms-cta",
          type: "cta",
          title: "Need Clarification?",
          body: "For official confirmation on admissions, fees, careers or policy matters, contact the school directly.",
          ctaLabel: "Contact School",
          ctaHref: "/contact-us",
        },
      ],
    },
  },
  privacy: {
    eyebrow: "Policy",
    title: "Privacy Policy",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1800&auto=format&fit=crop",
    body: [
      "Udaan World School respects the privacy of students, parents, staff, visitors and applicants. This page explains what website information may be collected and how it is used.",
    ],
    highlights: [],
    meta: {
      heroVariant: "full",
      sections: [
        {
          id: "privacy-overview",
          type: "split",
          eyebrow: "Data Use",
          title: "How Website Information Is Handled",
          body: "When you submit admission enquiries, contact forms, career applications or uploaded files, the information is stored for school communication, screening, documentation and administration.\n\nThis may include names, email addresses, phone numbers, academic details, resumes, uploaded documents and submitted messages.",
          mediaUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
          theme: "light",
        },
        {
          id: "privacy-points",
          type: "cards",
          title: "Privacy Commitments",
          body: "The school uses a practical, limited and admin-controlled approach to website data.",
          theme: "dark",
          columns: 2,
          items: [
            {
              title: "Form Data",
              text: "Information submitted through public forms is used only for school follow-up, administration and communication.",
              icon: "Mail",
            },
            {
              title: "Admin Access",
              text: "Only authorized admin users should access stored dashboard records, uploaded files and management tools.",
              icon: "ShieldCheck",
            },
            {
              title: "Published Media",
              text: "Public pages only display the content, documents, photos and videos that admins intentionally publish.",
              icon: "Camera",
            },
            {
              title: "Correction Requests",
              text: "Users may contact the school to request correction or removal of website-submitted information where appropriate.",
              icon: "UserCheck",
            },
          ],
        },
        {
          id: "privacy-cta",
          type: "cta",
          title: "Questions About Data?",
          body: "If you need help with stored form submissions, uploaded files or public content concerns, contact the school directly.",
          ctaLabel: "Get In Touch",
          ctaHref: "/contact-us",
        },
      ],
    },
  },
};
